### ISSUE TITLE
Investigate creating a dynamic site

### ISSUE THREAD

**Issue by smayya337** [Duosmium/duosmium-ruby#3]
Static sites have their advantages, but I've been toying with porting the site to a dynamic framework (i.e. Rails). Going dynamic would reduce the need to rebuild the site every time a new result is added, obsolete some of our helper scripts thanks to added database functionality, and probably make cool stuff like #2 possible. However, it does raise a number of issues with regards to how much the site will need to be rewritten and where it'll be hosted (Netlify doesn't do Rails apps). In any case, it's an interesting concept.

**Comment by smayya337** [comment]
Noting these here because they might be handy:  the Unosmium project already has two programs - [Sahara](https://github.com/unosmium/sahara) and [Kalahari](https://github.com/unosmium/kalahari) - that can convert SciolyFF to HTML and let us preview the results, which is cool.

**Comment by smayya337** [comment]
Update: progress has been decent so far. The main things missing are the award bubbles, modals, the "Upcoming" list, and the style for the "return to top" button on the schools list. I'll also need to probably add some form of authentication to prevent unauthorized addition of results. Unfortunately, school + other SciOly work has gotten in the way for now, but at least we've gotten this much done!

**Comment by smayya337** [comment]
I've created [a new repository](https://github.com/Duosmium/duosmium-rails) for this project and will be moving all updates there. Closing.

**Comment by BluePenguin18** [comment]
Hi Shreyas, my name is Varun Punnam, and I am a student at the Academy for Health and Medical Sciences in Bridgewater, New Jersey. On this topic, my school's results are grouped under a non-existent "Middlesex County Academy for Health and Medical Science (NJ)," which is an especially weird issue since my school is in Somerset County.
The confusion seems to arise from the real Middlesex County Academy for Science, Mathematics & Engineering Technologies being a nearby competitor. Ironically, that school is also facing reporting issues since their results are split between two nearly identical school names, with the only difference being the word "and" instead of an ampersand between "Mathematics" and "Engineering."
![github photo](https://user-images.githubusercontent.com/76894467/113525646-25f58080-9584-11eb-8bdc-319dcfba7460.png)

**Comment by smayya337** [comment]
@BluePenguin18 uh-oh... I would blame it on not having a team member from New Jersey, except we do - sorry about the error, I'll fix that ASAP, thanks for letting me know! (And yeah, the ampersand thing is always fun... we try to stick to "and" where possible, but not everyone is aware of that choice.)

EDIT: [hopefully I got all of them](https://duosmium.org/results/schools#Academy_for_Health_and_Medical_Sciences_(NJ))
